/*

 TILEMAP.H

 Map Include File.

 Info:
   Section       : bgmap
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : bg-gbtdesigner.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BGMapWidth 32
#define BGMapHeight 32
#define BGMapBank 0

extern unsigned char BGMap[];

/* End of TILEMAP.H */
